# Рабочая тетрадь №2

# Теоретический материал



## Задание 1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [5]:
import numpy as np

# Создаем матрицу 8x8 с нулями
matrix = np.zeros((8, 8), dtype = int)

# Заполняем её единицами с шахматным порядком
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Задание 1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [10]:
import numpy as np

matrix = np.arange(5).reshape(5, 1) + np.zeros((1, 5))
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


## Задание 1.3.3

Создать массив 3x3x3 со случайными значениями.

In [14]:
import numpy as np

arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.64996746 0.75980479 0.48783801]
  [0.03500392 0.61682632 0.54554409]
  [0.55770328 0.1373643  0.55730396]]

 [[0.86228155 0.06452926 0.64812614]
  [0.7244947  0.90830886 0.92633772]
  [0.08730685 0.86024817 0.11334048]]

 [[0.25656458 0.8940793  0.79920278]
  [0.33363758 0.78076034 0.87375613]
  [0.65746805 0.95343862 0.76156173]]]


## Задание 1.3.4

Создать матрицу с 0 внутри, и 1 на границах.

In [8]:
import numpy as np

# Создание матрицы из единиц
matrix = np.ones((5, 5))

# Замена неграничных элементов на нули
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Задание 1.3.5

Создайте массив и отсортируйте его по убыванию.

In [12]:
import numpy as np

# Создаем массив из 10 случайных чисел
arr = np.random.randint(0, 100, size=10)
 
# Сортируем по убыванию
arr_sorted = np.sort(arr)[::-1]

print(arr_sorted)

[96 92 86 80 63 56 56 53 38 10]


## Задание 1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [16]:
import numpy as np

# Создаем матрицу 3x4, заполненную нулями
matrix = np.zeros((3, 4)) 

print(matrix.shape) # Форма
print(matrix.size)  # Количество элементов
print(matrix.ndim)  # Размерность

(3, 4)
12
2


## Задание 2.3.1

Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [17]:
import pandas as pd
import numpy as np

# Создание двух точек
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

# Находим евклидово расстояние между двумя Series
d = np.sqrt(np.sum((a - b) ** 2))

print(d)

5.196152422706632
