# Рабочая тетрадь №2

## Теоретический материал

### Библиотека NumPy

NumPy (<b>Num</b>erical<b>Py</b>thon) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.
<p>Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
<br>&nbsp;&nbsp;pip install numpy
<p>Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
<br>&nbsp;&nbsp;import numpy as np
<p>Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.
<p>Наиболее важные атрибуты объектов ndarray:
<br><b>ndarray.ndim</b> - число измерений (чаще их называют "оси") массива.
<br><b>ndarray.shape</b> - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
<br><b>ndarray.size</b> - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
<br><b>ndarray.dtype</b> - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
<br><b>ndarray.itemsize</b> - размер каждого элемента массива в байтах.
<br><b>ndarray.data</b> - буфер, содержащий фактические элементы массива.
<p>Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.
<p>Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html

## Задание 1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy as np

# Создаем матрицу 8x8 с нулями
matrix = np.zeros((8, 8), dtype = int)

# Заполняем её единицами с шахматным порядком
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Задание 1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [10]:
import numpy as np

matrix = np.arange(5).reshape(5, 1) + np.zeros(5)
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


## Задание 1.3.3

Создать массив 3x3x3 со случайными значениями.

In [14]:
import numpy as np

arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.64996746 0.75980479 0.48783801]
  [0.03500392 0.61682632 0.54554409]
  [0.55770328 0.1373643  0.55730396]]

 [[0.86228155 0.06452926 0.64812614]
  [0.7244947  0.90830886 0.92633772]
  [0.08730685 0.86024817 0.11334048]]

 [[0.25656458 0.8940793  0.79920278]
  [0.33363758 0.78076034 0.87375613]
  [0.65746805 0.95343862 0.76156173]]]


## Задание 1.3.4

Создать матрицу с 0 внутри, и 1 на границах.

In [13]:
import numpy as np

# Создание матрицы из единиц
matrix = np.ones((5, 5))

# Замена неграничных элементов на нули
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Задание 1.3.5

Создайте массив и отсортируйте его по убыванию.

In [12]:
import numpy as np

# Создаем массив из 10 случайных чисел
arr = np.random.randint(0, 100, size=10)
 
# Сортируем по убыванию
arr_sorted = np.sort(arr)[::-1]

print(arr_sorted)

[96 92 86 80 63 56 56 53 38 10]


## Задание 1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [16]:
import numpy as np

# Создаем матрицу 3x4, заполненную нулями
matrix = np.zeros((3, 4)) 

print(matrix.shape) # Форма
print(matrix.size)  # Количество элементов
print(matrix.ndim)  # Размерность

(3, 4)
12
2


## Теоретический материал

### Библиотека Pandas

Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких источников.
<p><i>Библиотека pandas</i> – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то <i>pandas</i> – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для  ранения данных и работе с ними.
<p><i>Библиотека pandas</i> присутствует в стандартной поставке Anaconda. Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:
<br>&nbsp;&nbsp;pip install pandas
<br>Для импорта библиотеки используйте команду:
<br>&nbsp;&nbsp;import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.
<p><b>Series</b> – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.
<p><b>DataFrame</b> – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

## Задание 2.3.1

Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [17]:
import pandas as pd
import numpy as np

# Создание двух точек
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

# Находим евклидово расстояние между двумя Series
d = np.sqrt(np.sum((a - b) ** 2))

print(d)

5.196152422706632


## Задание 2.3.2

Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).