# Рабочая тетрадь №2

## Теоретический материал

### Библиотека NumPy

NumPy (<b>Num</b>erical<b>Py</b>thon) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.
<p>Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
<br>&nbsp;&nbsp;pip install numpy
<p>Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
<br>&nbsp;&nbsp;import numpy as np
<p>Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.
<p>Наиболее важные атрибуты объектов ndarray:
<br><b>ndarray.ndim</b> - число измерений (чаще их называют "оси") массива.
<br><b>ndarray.shape</b> - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
<br><b>ndarray.size</b> - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
<br><b>ndarray.dtype</b> - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
<br><b>ndarray.itemsize</b> - размер каждого элемента массива в байтах.
<br><b>ndarray.data</b> - буфер, содержащий фактические элементы массива.
<p>Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.
<p>Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html

## Пример 1.2.1

Задание:
<br>Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np
x = np.array([[2, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 2  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


## Пример 1.2.2

Задание:
<br>Выполнить следующее:

1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [2]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


## Пример 1.2.3

Задание:
<br>Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [3]:
import numpy as np

Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.003453549295651892 0.9852462354084204 0.5105661826353861


## Пример 1.2.4

Задание:
<br>Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [2]:
import numpy as np

A = np.arange(25).reshape(5,5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Пример 1.2.5

Задание:
<br>Выяснить результат следующих выражений:
<br>0 * np.nan
<br>np.nan == np.nan
<br>np.inf > np.nan
<br>np.nan - np.nan
<br>0.3 == 3 * 0.1

In [3]:
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 2 * 0.1)

nan
False
False
nan
False


## Пример 1.2.6

Задание:
<br>Отсортировать массив.

In [4]:
import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]



## Задание 1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy as np

# Создаем матрицу 8x8 с нулями
matrix = np.zeros((8, 8), dtype = int)

# Заполняем её единицами с шахматным порядком
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Задание 1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [10]:
import numpy as np

matrix = np.arange(5).reshape(5, 1) + np.zeros(5)
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


## Задание 1.3.3

Создать массив 3x3x3 со случайными значениями.

In [14]:
import numpy as np

arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.64996746 0.75980479 0.48783801]
  [0.03500392 0.61682632 0.54554409]
  [0.55770328 0.1373643  0.55730396]]

 [[0.86228155 0.06452926 0.64812614]
  [0.7244947  0.90830886 0.92633772]
  [0.08730685 0.86024817 0.11334048]]

 [[0.25656458 0.8940793  0.79920278]
  [0.33363758 0.78076034 0.87375613]
  [0.65746805 0.95343862 0.76156173]]]


## Задание 1.3.4

Создать матрицу с 0 внутри, и 1 на границах.

In [13]:
import numpy as np

# Создание матрицы из единиц
matrix = np.ones((5, 5))

# Замена неграничных элементов на нули
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Задание 1.3.5

Создайте массив и отсортируйте его по убыванию.

In [12]:
import numpy as np

# Создаем массив из 10 случайных чисел
arr = np.random.randint(0, 100, size=10)
 
# Сортируем по убыванию
arr_sorted = np.sort(arr)[::-1]

print(arr_sorted)

[96 92 86 80 63 56 56 53 38 10]


## Задание 1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [16]:
import numpy as np

# Создаем матрицу 3x4, заполненную нулями
matrix = np.zeros((3, 4)) 

print(matrix.shape) # Форма
print(matrix.size)  # Количество элементов
print(matrix.ndim)  # Размерность

(3, 4)
12
2


## Теоретический материал

### Библиотека Pandas

Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких источников.
<p><i>Библиотека pandas</i> – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то <i>pandas</i> – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для  ранения данных и работе с ними.
<p><i>Библиотека pandas</i> присутствует в стандартной поставке Anaconda. Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:
<br>&nbsp;&nbsp;pip install pandas
<br>Для импорта библиотеки используйте команду:
<br>&nbsp;&nbsp;import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.
<p><b>Series</b> – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.
<p><b>DataFrame</b> – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

## Пример 2.2.1

Задание:
<br>Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [10]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


## Пример 2.2.2

Задание:
<br>Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [9]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


## Пример 2.2.3

Задание:
<br>Создайте новый фрейм данных.

In [11]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

## Пример 2.2.4

Задание:
<br>Загрузите фрейм данных по ссылке:
<br>https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [2]:
import pandas as pd

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

## Пример 2.2.5

Задание:
<br>Пронализировать характеристики фрейма данных.

In [6]:
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [8]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [9]:
dataframe.shape

(1313, 6)

In [10]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

## Пример 2.2.6

Задание:
<br>Выберите индивидуальные данные или срезы фрейма данных.

In [11]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

## Пример 2.2.7

Задание:
<br>Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [12]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

## Задание 2.3.1

Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [17]:
import pandas as pd
import numpy as np

# Создание двух точек
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

# Находим евклидово расстояние между двумя Series
d = np.sqrt(np.sum((a - b) ** 2))

print(d)

5.196152422706632


## Задание 2.3.2

Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных.

In [2]:
import pandas as pd

# Указываем URL-адрес файла, который хотим загрузить
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'

# Загружаем данные в объект dataframe
dataframe = pd.read_csv(url)

# Выводим первые 5 строк таблицы
dataframe.head(5)

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
0  0.271  0.328   74  161  22  6  12   58  49  133  23  17   1   1   0   0   
1  0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2  0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3  0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   
4  0.206  0.262   14   51  18  1   1   28  17   26   0   3   1   1   0   0   

   salary  
0     109  
1     160  
2    2700  
3     550  
4     300

## Задание 2.3.3

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [29]:
import pandas as pd

# Указываем URL-адрес файла, который хотим загрузить
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'

# Загружаем данные в объект dataframe
dataframe = pd.read_csv(url)

# Выводим первые 5 строк таблицы
dataframe.head(5)

# Выводит последние 3 строки
dataframe.tail(3)

# Возвращает количество строк и столбцов
dataframe.shape

# Выбирает каждую 4-ую строку, начиная с индекса 1
dataframe.iloc[1::4]

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
1    0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
5    0.238  0.272   53  106  18  3  15   59  22  107  14   7   0   0   0   0   
9    0.266  0.359  115  152  32  1  44  122  78  152  26   9   1   0   0   0   
13   0.285  0.380   96  157  30  3   3   50  83   36  35   8   1   0   0   0   
17   0.247  0.306   65  114  14  9   6   52  36   60  15   3   1   1   0   0   
..     ...    ...  ...  ...  .. ..  ..  ...  ..  ...  ..  ..  ..  ..  ..  ..   
317  0.275  0.377   67  109  25  1  21   87  65   81   8   7   0   0   0   0   
321  0.252  0.301   15   35   5  1   5   22  10   23   1   0   0   0   1   0   
325  0.275  0.351   40   70  16  4   4   21  30   42  15   3   1   1   0   0   
329  0.262  0.283    7   38   5  0   0   10   5   18   2   7   0   0   0   0   
333  0.288  0.366   24   47   7  0   7   24  18   23   2   3   0   0   0   0   

     salary  
1       160  
5       230  
9      4300  
13     2000  
17     1050  
..      ...  
317     555  
321     425  
325     935  
329     177  
333     525  

[84 rows x 17 columns]

In [28]:
# Возвращает статистическую информацию для числовых столбцов
dataframe.describe()

1           2           3           4           5           6  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     0.257825    0.323973   46.697329   92.833828   16.673591    2.338279   
std      0.039546    0.047132   29.020166   51.896322   10.452001    2.543336   
min      0.063000    0.063000    0.000000    1.000000    0.000000    0.000000   
25%      0.238000    0.297000   22.000000   51.000000    9.000000    0.000000   
50%      0.260000    0.323000   41.000000   91.000000   15.000000    2.000000   
75%      0.281000    0.354000   69.000000  136.000000   23.000000    3.000000   
max      0.457000    0.486000  133.000000  216.000000   49.000000   15.000000   

                7           8           9          10          11          12  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     9.097923   44.020772   35.017804   56.706231    8.246291    6.771513   
std      9.289934   29.559406   24.842474   33.828784   11.664782    5.927490   
min      0.000000    0.000000    0.000000    1.000000    0.000000    0.000000   
25%      2.000000   21.000000   15.000000   31.000000    1.000000    3.000000   
50%      6.000000   39.000000   30.000000   49.000000    4.000000    5.000000   
75%     15.000000   66.000000   49.000000   78.000000   11.000000    9.000000   
max     44.000000  133.000000  138.000000  175.000000   76.000000   31.000000   

               13          14          15          16       salary  
count  337.000000  337.000000  337.000000  337.000000   337.000000  
mean     0.397626    0.115727    0.192878    0.029674  1248.528190  
std      0.490135    0.320373    0.395145    0.169938  1240.013309  
min      0.000000    0.000000    0.000000    0.000000   109.000000  
25%      0.000000    0.000000    0.000000    0.000000   230.000000  
50%      0.000000    0.000000    0.000000    0.000000   740.000000  
75%      1.000000    0.000000    0.000000    0.000000  2150.000000  
max      1.000000    1.000000    1.000000    1.000000  6100.000000

In [30]:
# Выборка из датафрейма, где значение столбца 'salary' больше или равно 500,
# и вывод первых двух строк выборки.
dataframe[dataframe['salary'] >= 500].head(2)

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
2  0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3  0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   

   salary  
2    2700  
3     550

## Теоретический материал

### Работа с числовыми данными

Количественные данные что-то измеряют – будь то размер класса, ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов, $529 392 продаж).
<p><b><i>Нормализация данных</i></b> — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
<p>Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.

На практике наиболее распространены следующие методы нормализации признаков:
- <b><i>Минимакс</i></b> – линейное преобразование данных в диапазоне [0..1], где минимальное и максимальное масштабируемые значения соответствуют 0 и 1 соответственно;
- <b><i>Z-масштабирование</i></b> данных на основе среднего значения и стандартного отклонения: производят деление разницы между переменной и средним значением на стандартное отклонение.

Нормализация по методу <b>минмакс</b>:
$$
  X_{norm} = \frac{X-X_{min}}{X_{max} - X_{min}}
$$
<br><b>Z-масштабирование</b>:
$$
  z = \frac{x - μ}{σ}
$$
<p>При масштабировании данных мы будем использовать одну из популярных библиотек машинного обучения <i>Scikit-learn</i>. Библиотека содержит пакет sklearn.preprocessing, который предоставляет широкие возможности для нормализации данных. Следует отметить, что в целом алгоритмы обучения выигрывают от стандартизации набора данных.

## Пример 3.2.1

Задание:
<br>Прошкалируйте числовой признак в диапазон между двумя значениями.

In [13]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

## Пример 3.2.2

Задание:
<br>Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [23]:
import numpy as np
from sklearn import preprocessing

x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [21]:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


## Пример 3.2.3

Задание:
<br>Дан фрейм данных
<br>dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'B':[103.02,107.26,110.35,114.23,114.68],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'C':['big','small','big','small','small']})
<br>Необходимо масштабировать его числовые столбцы.

In [27]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big', 'small', 'big', 'small', 'small']})

dfTest[['A', '8']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A       B      C         8
0  0.000000  103.02    big  0.000000
1  0.926219  107.26  small  0.363636
2  0.935335  110.35    big  0.628645
3  1.000000  114.23  small  0.961407
4  0.938495  114.68  small  1.000000

## Задание 3.3.2

Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [38]:
import pandas as pd
from sklearn import preprocessing

# Указываем URL-адрес файла, который хотим загрузить
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

# Загружаем данные в объект dataframe
dataframe = pd.read_csv(url)

# Создание шкалировщиков
minmax_scaler = preprocessing.MinMaxScaler()
z_scaler = preprocessing.StandardScaler()

# Прошкалирование
dataframe[['sepal_length_cm']] = minmax_scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = z_scaler.fit_transform(dataframe[['sepal_width_cm']])

# Вывод после применения методов нормализации
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]